Se agrega AnimationController para manejo de animaciones para sprite …
gamerevar/proyecto-comunitario-1-gd pull request #88
Opened 2021-01-03 10:29 UTC by jjmontes

…sheets de 10x10 con animaciones básicas de direcciones

2021-01-03 20:31 UTC, azagaya requested changes

2021-01-03 20:31 UTC, azagaya commented on scenes/AnimationController/AnimationController.gd
> +
Según la convención elegída, usamos "snake_case" para nombres de variables. Acá estás usando "lowerCamelCase". En la variable `_animationTree` (que debería ser `_animation_tree`) además puede inferirse el tipo automáticamente, y en la convención se usa eso siempre que se pueda. Además se debe dejar espacio entre el nombre de la variable y los dos puntos. Debería ser así:

```gd
onready var _animation_tree := $AnimationTree
onready var _animation_state := $AnimationNodeStateMachinePlayback = _animation_tree.get("parameters/playback")
```

2021-01-03 20:31 UTC, azagaya commented on scenes/AnimationController/AnimationController.gd
> +func play_animation(name: String, direction: Vector2) -> void:
No estas usando el parámetro `name` de la función. La idea sería que en la última línea en lugar de `"Walk"` pongas `name`.

2021-01-03 20:34 UTC, azagaya commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
Otro comentario, probablemente la dirección sea un vector normalizado, vos acá necesitas que el diagonal sea por ejemplo `Vector2(1, 1)`. O cambiamos las coordenadas en el blend state, o al comienzo de la función haces que el vector normalizado tome siempre valores 1 o 0 en la función.

2021-01-03 22:26 UTC, jh62 commented on scenes/AnimationController/AnimationController.tscn
> +start_node = "Idle"
@azagaya Creo que las animaciones del tree deberian ser en snake_case tb.

2021-01-04 09:46 UTC, jjmontes commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
El control AnimationTree, según las pruebas que hice, no necesita un vector normalizado, si el vector que pasas cae fuera de cualquier rango de animación, lo interpreta al rango "más cercano"

Actualmente estamos usando rangos de -1 a 1, pero si quisieramos definir animaciones de correr (el único ejemplo que se me ocurre con un rango mayor a [-1..1]) en un rango mayor al 1 (por ejemplo, ABS(1) a ABS(2)) podríamos definir las animaciones correspondientes en ese rango.

De todas formas, si considerás que lo mejor sea que pasemos un vector normalizado, lo normalizo como primer línea dentro de la función
```suggestion
func play_animation(name: String, direction: Vector2) -> void:
	direction = direction.normalize()
	if direction == Vector2.ZERO:
```

2021-01-04 09:55 UTC, jjmontes commented on scenes/AnimationController/AnimationController.tscn
> +start_node = "Idle"
@jh62 me parece que tenés razón, sería bueno definir nosotros nuestra propia convención, ya que en la documentación de convenciones no vi nada al respecto, y si te fijás las convenciones que usan en la documentación de godot  sobre animaciones usan cosas mezcladas indiscriminadamente.

Por ejemplo, acá https://docs.godotengine.org/en/3.2/tutorials/animation/animation_tree.html#state-machine-travel usan como nombre de la animación "SomeState", pero en esta imagen 
![imagen](https://user-images.githubusercontent.com/576414/103522569-53ce0a80-4e59-11eb-87a3-40c34a7348e4.png)
usan indistintamente Idle-cycle (ya mezclado **I**dle con **c**ycle) y running_gun-cycle.

2021-01-04 09:59 UTC, jjmontes commented
@azagaya según lo que hablamos en discord ayer ¿te parece que también agregue animaciones para Death y Attack? Así ya dejamos todo eso resuelto e incluido en esta tarea.

2021-01-04 10:05 UTC, azagaya commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
En realidad me referia a lo siguiente. Las animaciines diagonales estan por ejemplo en (1, 1) (1, -1) (-1, -1) (-1, 1), pero que pasa si le paso `Vector2(1,1).normalized()` a la funcion? Toma bien la anim de (1,1)? Al ser una direccion, la gente qur la use probablemente asuma que debe estar normalizada. Eso lo probaste?

2021-01-04 10:06 UTC, azagaya commented
> @azagaya según lo que hablamos en discord ayer ¿te parece que también agregue animaciones para Death y Attack? Así ya dejamos todo eso resuelto e incluido en esta tarea.

Si, me parece que estaria bien agregarlad

2021-01-04 10:32 UTC, jjmontes commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
Creo que me perdí en algo, porque si haces Vector2(1,1).normalized() eso devuelve un Vector2(1,1).

Más allá de eso, probé normalizando y no normalizando y funciona en ambos casos. Incluso, no tiene que ser "exactamente" 1,1. 

Fijate acá:
![imagen](https://user-images.githubusercontent.com/576414/103525508-1ddf5500-4e5e-11eb-8c21-9732d455c144.png)
no son puntos, sinó, triangulos y te toma una buena parte del triángulo, aunque no toda. Te paso una animación

![AnimationTree - Triangulos](https://user-images.githubusercontent.com/576414/103525786-98a87000-4e5e-11eb-92d2-2756680d3af0.gif)

Si te fijás, no es exacto y va tomando la animación más o menos según la línea del triangulo. Está tomando secciones de 0,1 (según la configuración del AnimatioTree) para calcular donde comienza y termina cada animación.

PD: No te fijes en la parte en que si apuntás arriba la animación que se ejecuta es hacia abajo... eso es porque la grilla del juego de Godot es negativa hacia arriba y la grilla del AnimationTree es negativa hacia abajo. O_o    -_-

No se si con eso respondí la duda que tenías

2021-01-04 11:14 UTC, azagaya commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
Ah si anda esta ok entonces.. era una duda. Para expandir.. Vector2(1,1) no es un vector normalizado, ya que su longitud es sqrt(2). Vector2(1,1).normalized() deberia devolver un Vector2(sqrt(2)/2, sqrt(2)/2)

2021-01-04 12:39 UTC, jjmontes commented on scenes/AnimationController/AnimationController.gd
> +	if direction == Vector2.ZERO:
Que boludo!! Tenés razón!

2021-01-06 15:55 UTC, azagaya approved these changes

2021-01-07 20:24 UTC, azagaya commented
@jjmontes Por ahí podrías sacar los assets de la carpeta assets, y ponerlos en una carpeta en TestScenes... porque sino necesitamos el aprove de @Ecoabismo , y en realidad no son assets posta.

2021-01-07 22:12 UTC, jjmontes commented
> @jjmontes Por ahí podrías sacar los assets de la carpeta assets, y ponerlos en una carpeta en TestScenes... porque sino necesitamos el aprove de @Ecoabismo , y en realidad no son assets posta.

Listo!

2021-01-08 17:55 UTC, Ecoabismo approved these changes

2021-01-09 19:35 UTC, merged